spring:
  profiles:
    active:
    - local
    

---

spring:
  profiles: local
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      '[hibernate.format_sql]' : true
  datasource:
    url: jdbc:h2:~/test;
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    '[org.hibernate.sql]': debug
    

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080

